name: Test Cypress Real World App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          ref: develop
          path: ./cloned-repo

      - name: Install Dependencies and Run Dev Server
        run: |
          cd cloned-repo
          yarn install
          yarn dev & sleep 15 && curl http://localhost:3000

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test:headless
          npm run report:generate
      - name: Create Report
        if: always()
        run: npm run allure:generate
      - name: Upload artifact allure-report
        uses: actions/upload-artifact@v1
        if: always()
        with:
              name: allure-report
              path: ./allure-report
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@3.1.0
        if: always()
        with:
              ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
              BRANCH: master
              FOLDER: allure-report
              TARGET_FOLDER: docs

